import puppeteer from "puppeteer";
import Order from "../models/Order.js";

const formatDate = (value) => {
  if (!value) return "N/A";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "Invalid Date";
  return date.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
};

const buildHtmlReport = ({ status, startDate, endDate, orders, totalOrders, deliveredOrders, cancelledOrders, totalRevenue }) => {
  const orderRows = orders.length
    ? orders
        .map(
          (order) => `
            <tr>
              <td>${order._id}</td>
              <td>${order.status}</td>
              <td>₹${order.amount.toFixed(2)}</td>
            </tr>
          `
        )
        .join("")
    : `
          <tr>
            <td colspan="3" style="text-align: center; font-style: italic; color: #6b7280;">No orders found</td>
          </tr>
        `;

  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>BookHeaven Report</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background: #f4f6fb;
            color: #20232a;
          }
          .container {
            max-width: 900px;
            margin: 0 auto;
            background: #ffffff;
            padding: 28px;
            border-radius: 12px;
            box-shadow: 0 4px 24px rgba(0, 0, 0, 0.08);
          }
          .header {
            background: #1f2937;
            color: #ffffff;
            padding: 24px;
            border-radius: 12px;
            margin-bottom: 24px;
          }
          .header h1 {
            margin: 0 0 8px;
            font-size: 28px;
          }
          .header p {
            margin: 0;
            color: #d1d5db;
            font-size: 14px;
          }
          .section {
            margin-bottom: 22px;
          }
          .section h2 {
            font-size: 18px;
            margin-bottom: 12px;
            color: #111827;
          }
          .summary-grid {
            display: grid;
            grid-template-columns: repeat(4, minmax(0, 1fr));
            gap: 14px;
          }
          .summary-card {
            background: #f8fafc;
            border: 1px solid #e5e7eb;
            padding: 16px;
            border-radius: 10px;
          }
          .summary-card strong {
            display: block;
            font-size: 24px;
            margin-bottom: 4px;
          }
          .summary-card span {
            color: #6b7280;
            font-size: 13px;
          }
          .report-meta {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 14px;
            margin-bottom: 20px;
          }
          .meta-card {
            background: #f8fafc;
            border: 1px solid #e5e7eb;
            border-radius: 10px;
            padding: 16px;
          }
          .meta-card p {
            margin: 4px 0;
            font-size: 14px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
          }
          thead {
            background: #111827;
            color: #ffffff;
          }
          th,
          td {
            padding: 12px 14px;
            border: 1px solid #e5e7eb;
            text-align: left;
            font-size: 13px;
          }
          tbody tr:nth-child(even) {
            background: #f8fafc;
          }
          .footer {
            margin-top: 24px;
            font-size: 12px;
            color: #6b7280;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>BookHeaven Report</h1>
            <p>Generated for BookHeaven admin panel</p>
          </div>

          <div class="report-meta">
            <div class="meta-card">
              <h2>Admin</h2>
              <p><strong>BookHeaven</strong></p>
              <p>Report generated by admin panel.</p>
            </div>
            <div class="meta-card">
              <h2>Filter Summary</h2>
              <p><strong>Status:</strong> ${status}</p>
              <p><strong>Start Date:</strong> ${formatDate(startDate)}</p>
              <p><strong>End Date:</strong> ${formatDate(endDate)}</p>
            </div>
          </div>

          <div class="section">
            <h2>Order Summary</h2>
            <div class="summary-grid">
              <div class="summary-card">
                <strong>${totalOrders}</strong>
                <span>Total Orders</span>
              </div>
              <div class="summary-card">
                <strong>${deliveredOrders}</strong>
                <span>Delivered</span>
              </div>
              <div class="summary-card">
                <strong>${cancelledOrders}</strong>
                <span>Cancelled</span>
              </div>
              <div class="summary-card">
                <strong>₹${totalRevenue.toFixed(2)}</strong>
                <span>Total Revenue</span>
              </div>
            </div>
          </div>

          <div class="section">
            <h2>Orders</h2>
            <table>
              <thead>
                <tr>
                  <th>Order ID</th>
                  <th>Status</th>
                  <th>Amount</th>
                </tr>
              </thead>
              <tbody>
                ${orderRows}
              </tbody>
            </table>
          </div>

          <div class="footer">
            <p>Generated on ${new Date().toLocaleString("en-GB", {
              day: "2-digit",
              month: "2-digit",
              year: "numeric",
              hour: "2-digit",
              minute: "2-digit",
            })}</p>
          </div>
        </div>
      </body>
    </html>
  `;
};

export const generateReport = async (req, res) => {
  let browser = null;
  try {
    const { status = "All", startDate, endDate } = req.query;

    const query = {};
    if (status && status !== "All") {
      query.status = status;
    }

    if (startDate) {
      const start = new Date(startDate);
      if (!Number.isNaN(start.getTime())) {
        query.createdAt = { ...query.createdAt, $gte: start };
      }
    }

    if (endDate) {
      const end = new Date(endDate);
      if (!Number.isNaN(end.getTime())) {
        end.setHours(23, 59, 59, 999);
        query.createdAt = { ...query.createdAt, $lte: end };
      }
    }

    const orders = await Order.find(query)
      .populate("items.product address")
      .sort({ createdAt: -1 });

    const totalOrders = orders.length;
    const deliveredOrders = orders.filter((order) => order.status === "Delivered").length;
    const cancelledOrders = orders.filter((order) => order.status === "Cancelled").length;
    const totalRevenue = orders.reduce((sum, order) => sum + (order.amount || 0), 0);

    const html = buildHtmlReport({
      status,
      startDate,
      endDate,
      orders,
      totalOrders,
      deliveredOrders,
      cancelledOrders,
      totalRevenue,
    });

    // Launch browser with optimized settings for stability
    browser = await puppeteer.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--no-first-run',
        '--no-zygote',
        '--disable-gpu',
        '--disable-web-security',
        '--disable-features=VizDisplayCompositor'
      ],
      timeout: 60000
    });

    const page = await browser.newPage();

    try {
      await page.setContent(html, { waitUntil: 'domcontentloaded' });

      // Wait for page to be fully loaded and stable
      await new Promise(resolve => setTimeout(resolve, 1000));

      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: {
          top: '20px',
          right: '20px',
          bottom: '20px',
          left: '20px'
        },
        preferCSSPageSize: true
      });

      res.set({
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename=BookHeaven_Report.pdf',
      });

      res.send(pdfBuffer);
    } finally {
      await page.close();
    }
  } catch (error) {
    console.error('Report generation error:', error);
    return res.status(500).json({ success: false, message: 'Unable to generate report' });
  } finally {
    if (browser) {
      await browser.close();
    }
  }
};
